@JwtAuthLearn_HostAddress = https://localhost:7097
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoid29vbGllIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJlMGZjY2FkMy01MTViLTQ5ZmQtYWY2NC04MzE5MThmZTI0ZjEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc2MjA2OTAyMiwiaXNzIjoiSnd0QXV0aExlYXJuIiwiYXVkIjoiSnd0QXV0aExlYXJuQXVkaWVuY2UifQ.TPi8shbDDTCwyrVf80BzEHxpoWNsblBTgmguUx9W1aP41TWqiR4nbhKN6Xmul5-ou2jJv_HrU5yxNeh4jyVU0g
### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

###

### Login User
POST {{JwtAuthLearn_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "woolie",
  "password": "woolie"
}
###

### Authenticated Only Endpoint
GET {{JwtAuthLearn_HostAddress}}/api/auth
Authorization: Bearer {{token}}

### Authenticated Only Endpoint
GET {{JwtAuthLearn_HostAddress}}/api/auth/admin-only
Authorization: Bearer {{token}}